import assert from 'node:assert/strict';
import fs from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {importModel} from '../assets/runtime/import-model.mjs';
import {Actor} from '../assets/runtime/actor.mjs';
const compressed=fs.readFileSync(new URL('../models/level-01.astro.gz',import.meta.url));
const arrayBuffer=b=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);
const raw=gunzipSync(compressed),modern=await importModel(arrayBuffer(compressed));
assert.deepEqual(Buffer.from(modern),raw);
const prefix=Buffer.from('<?php http_response_code(404); exit; __halt_compiler();\n');
const legacy=Buffer.concat([prefix,raw.subarray(8)]);
assert.deepEqual(Buffer.from(await importModel(arrayBuffer(legacy))),raw);
assert.ok(new Actor(modern).spec.encoder_version===1);
const bad=raw.slice();bad.writeFloatLE(NaN,raw.length-4);
assert.throws(()=>new Actor(arrayBuffer(bad)),/Non-finite/);
const corrupted=Buffer.from(compressed);corrupted[corrupted.length-6]^=1;
await assert.rejects(()=>importModel(arrayBuffer(corrupted)));
await assert.rejects(()=>importModel(arrayBuffer(Buffer.from('<?php echo "not model data";'))));
assert.throws(()=>new Actor(new ArrayBuffer(0)),/Invalid model/);
console.log('PASS gzip and legacy PHP data imports; malformed, corrupt, and non-finite models rejected');
